### ISSUE TITLE
Eloquent Model creation assigning ID=0

### ISSUE THREAD

**Issue by jcorrego** [laravel/telescope#289]
I dont know why, but i had a weird case with just one eloquent model, or at least have just detected this case, when i do a try to create by any of the possible ways : 
```
new XXX; xxx->save();
XXX:create
auth()->user()->xxxs()->create()
```
In all cases i get an id assigned of `0`, and of course the record is not saved, but i dont get any error...
I then edit telescope config file, and commented all the watchers, and the code works again, records are saved...
This only happens in production environment. And also tested with `tinker` in production and cretion works ok...

**Comment by themsaid** [comment]
How is this Telescope related?

**Comment by jcorrego** [comment]
> How is this Telescope related?

This just happened after installing telescope, and like i said inactivating the watchers, everything works fine, aso soon as i activate them, model create gets id=0

**Comment by jeremeallen** [comment]
Changing my .env file to:

APP_ENV=production

Then trying something like:

```
        $submission = Test::create([
            'name' => 'Test name'
        ]);

        dd($submission->id);
```

Always returns id = 0 with the .env set to production.  Set .env to local and the id auto increment is returned.

If I have .env set to production and in the TelescopeServiceProvider, I do this:

```
        Telescope::filter(function (IncomingEntry $entry) {
            return true;
```

Then I get ids returned in production

**Comment by JohnYeohMY** [comment]
i have the same problem. but i heard that telescope is not for production use right?

**Comment by themsaid** [comment]
I can't replicate this issue, can someone please try on a fresh laravel installation? Seems there's something special in your applications that we need to figure out.

**Comment by jeremeallen** [comment]
Agreed I can't reproduce on a new project either.  Fired up a new project, added in components one by one .... I match packages and versions and everything works as expected in a new Laravel install.

```
"require": {
        "php": "^7.1.3",
        "barryvdh/laravel-cors": "^0.11.2",
        "fideloper/proxy": "^4.0",
        "hisorange/browser-detect": "^3.1",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "rollbar/rollbar-laravel": "^4.0",
        "tedivm/jshrink": "^1.3"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "laravel/telescope": "^0.1.5",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
```

Understand the issue is with my existing app and code.

**Comment by richfoxton** [comment]
I was having a similar issue. A Horizon job kept failing on my production server after telescope had been added (even though it was only a dev dependency) - the same job was working fine on my dev machine. See error below...

![image](https://user-images.githubusercontent.com/5740463/47942709-d27e3480-deea-11e8-9a59-b47e325d8f11.png)

Temporarily changed the .env file to local and debug to true on production and it started working again. Removed telescope completely from project and the job worked again.

See log below...first job had .env variables set to local, second (failed) was with production, third with production variables after removing telescope completely. Nothing else changed.

![image](https://user-images.githubusercontent.com/5740463/47942764-0b1e0e00-deeb-11e8-81e3-ddac9c2416ea.png)

**Comment by malekhijazi** [comment]
I'm facing the same problem. 
After saving the id is 0. 

If I change the APP_ENV to "local" everything works fine 
When I change the APP_ENV to "production" or "development" the issue happens.

**Comment by themsaid** [comment]
@malekhijazi after saving, is the record stored in the DB or not?

**Comment by malekhijazi** [comment]
@themsaid yes its saving in the database but after $model->save(), $model->id is being returned 0 but all other attributes are correct. 

I have the ID as auto increment and im not manually assigning the id

**Comment by mojosef** [comment]
After updating to telescope 0.1.6, `$model->id` now returns `null`. However, the model is still saving.

**Comment by themsaid** [comment]
@malekhijazi so if you disable the QueryWatcher but keep the ModelWatcher it works?

**Comment by malekhijazi** [comment]
@themsaid yes.

Setting this
` Watchers\QueryWatcher::class => [
            'enabled' => env('TELESCOPE_QUERY_WATCHER', false),
            'slow' => 100,
        ],`

or
`Watchers\QueryWatcher::class => [
         'enabled' => env('TELESCOPE_QUERY_WATCHER', true),
            'slow' => 0,
        ],`
 
works

**Comment by paras-malhotra** [comment]
Which version/release of Telescope are you guys using?

**Comment by malekhijazi** [comment]
@paras-malhotra "laravel/telescope": "^0.1.6",

**Comment by mojosef** [comment]
@paras-malhotra "laravel/telescope": "^0.1.6", ( Same on 0.1.5 )

**Comment by leonardochen30** [comment]
Is for the first query executed

**Comment by malinky** [comment]
I faced a similar issue on Forge with APP_ENV=production. Local environment is fine. After $model->save() the ID returned is 0. The record is saved in the database.

I've since removed Telescope on production and it is working again.

I upgraded the Laravel app from 5.5 through to 5.7.11 to install Telescope (v0.1.2).

**Comment by staudenmeir** [comment]
This issue reminds me of https://github.com/laravel/framework/issues/25768#issuecomment-424179984.

Could it be that the `QueryWatcher` executes a query directly after the query it's listening to? This would override the connection's `lastInsertId()` value with `0` (if it's a non-`INSERT` query).

**Comment by themsaid** [comment]
Everyone reported this, are you using the same connection of your app to store Telescope entries?

**Comment by csanda87** [comment]
Yes they all use the same db connection.

**Comment by themsaid** [comment]
@csanda87  is the issue resolved if you use a separate connection? Which is recommended since you don't want Telescope to slow down your database server in case recording went out of hand.

**Comment by themsaid** [comment]
This is now fixed guys.

**Comment by jihadismail8** [comment]
i still have the same problem

**Comment by cbaconnier** [comment]
The issue seems back.
I have set `'enabled' => env('TELESCOPE_QUERY_WATCHER', true),` to `false` and now it's working.

    Watchers\QueryWatcher::class => [
            'enabled' => env('TELESCOPE_QUERY_WATCHER', false),
            'ignore_packages' => true,
            'slow' => 100,
        ],

Thank to @malekhijazi for the comment.

**Telescope 2.0.5**
**Laravel 5.8.26**

And I do believe I had the issue with Laravel 5.8.23.

**Comment by bcorcoran** [comment]
I can confirm along with @cbaconnier that this seems to be back. Why is the query watcher modifying the primary key / id?

I notice that if i dump the model, id:0 is placed at the end of the object. With query watcher disabled, id is first and has the correct value.

This wasted a lot of time; I thought I was doing something wrong.

**Comment by tormjens** [comment]
I've also noticed this issue in one of my projects running latest of both Laravel and Telescope.

Disabling the query watcher does indeed make it work, but the query watcher is a neat thing to have in local/staging.

I would also like to know why the query watcher would be modifying primary key/id. I feel the behavior is kind of strange.

**Comment by bcorcoran** [comment]
@themsaid any input on this?

**Comment by barryvdh** [comment]
When a query is fired inside the `QueryExecuted` event, it will overwrite the lastInsertId. This is probably happening inside `withoutRecording` so it isn't logged. But maybe you can create your own logger?

```php
use Illuminate\Database\Events\QueryExecuted;
use Illuminate\Support\Facades\Event;

    public function boot()
    {
        Event::listen(QueryExecuted::class, function($event) {
            dump($event->sql);
        });
    }
```

That way, we can narrow down what is causing the extra query.

You aren't using any custom tagging/after recording hook? Or perhaps disable the retrieving of the user inside the `record` method from Telescope (if your model/auth is different somehow)

**Comment by bcorcoran** [comment]
@barryvdh No custom tagging or hooks. Not even using this with a user, so auth is irrelevant. In fact I was only trying to use $model->associate($newItem) and it was inserting 0 as the ID in the pivot table.

This is obviously a bug... and at best it's bad (and undocumented) behavior.

**Comment by barryvdh** [comment]
Not saying that it isn't, but just trying to help narrow it down.

**Comment by bcorcoran** [comment]
I apologize for my tone-you're totally right.

That said, I have not done anything with telescope at all other than install/view it. I don't think my model setup is strange in any way- I'm doing only things listed in the documentation.

Thinking about it now though, is it possible this could be conflicting with https://github.com/owen-it/laravel-auditing ?

**Comment by barryvdh** [comment]
No experience with that.
I do feel that the current behavior of Laravel itself might be a bit confusing. Ideally the query event would be executed after getting the lastInsertId, otherwise conflicts are bound to happen (had this case with debugbar also once)

Not sure why laravel-auditing would run any queries. There are some Eloquent models created, but it only watches for whitelisted models, right?

**Comment by bcorcoran** [comment]
As far as I understand it, yes. It's the only thing I didn't write (other than things provided by laravel itself) that I'm using on the model, so it is the only thing that came to mind.

**Comment by barryvdh** [comment]
So did you try dumping queries? Does anything come after the insert?

**Comment by barryvdh** [comment]
Wouldn't it be possible for Telescope to force a new connection? Eg. copy the current connections etc (if default) and create a second connection for it? So they can never interfere?

**Comment by barryvdh** [comment]
So did anyone try to dump the queries? I can't replicate this and am kinda worried about this breaking anything, but seems unlikely. Can you also check you are running `v2.0.6`?

**Comment by tormjens** [comment]
I'm still experiencing this. Did anyone manage to come up with a solution that does not turn off the query watcher?

**Comment by piperone** [comment]
I put this into a model I was trying to persist.

`php
public static function boot()
{
    parent::boot();
    Event::listen(QueryExecuted::class, function($event) {
        \Log::info($event->sql);
    });
}
`

The relevant output is as follows:

`
local.INFO: insert into `my_table` (`field`, `second_field`, `third_field`, `fourth_field`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?)  

local.INFO: {"field":"foo","second_field":"bar","third_field":null,"fourth_field":10,"updated_at":"2020-03-23 12:11:47","created_at":"2020-03-23 12:11:47","id":0}

local.INFO: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `family_hash`, `type`, `uuid`) values (?, ?, ?, ?, ?, ?) - A bunch of (?, ? ...) follows 

local.INFO: insert into `telescope_entries_tags` (`entry_uuid`, `tag`) values (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
`

It doesn't tell me much other than the fact that the id has been changed to 0. What about you, @barryvdh ?

**Comment by thijndehaas** [comment]
This also is happening on my Laravel setup and only in production. I changed TELESCOPE_QUERY_WATCHER to false and this fixed the problem.

PHP 7.4.4
MariaDB 10.2.31
laravel/telescope  v3.2.1
laravel/framework v7.6.2

```
APP_ENV=production
APP_DEBUG=true
```

Can we test anything else?

**Comment by bcorcoran** [comment]
This is still happening on Laravel 8.17.1 and Telescope 4.3.1. Local env.

`TELESCOPE_QUERY_WATCHER=false` is the only way that I can avoid this issue at present.

Any model that I try to return an ID from returns 0.

This also happens while doing $model->relationship()->create([]);

Both models are created successfully, but the relationship ID is saved as 0, which breaks the application.

**Comment by darinda** [comment]
I stumbled upon this issue and thought i had the same problem, turned out in my case it looked the same (id being 0 after creation) but actually was not related to telescope. In fact in my case the corresponding model did not use auto increment keys (but a separate column) but i forgot to add `public $incrementing = false;` to that model. 

Maybe this could be helpful for others discovering this issue via google.

**Comment by alex-p-ysbm** [comment]
In our case the issue occurs because an extra query is executed in the user's 'email getter. The watcher [tries](https://github.com/laravel/telescope/blob/3.x/src/Telescope.php#L268) to [log the auth user](https://github.com/laravel/telescope/blob/3.x/src/IncomingEntry.php#L147) so the query is executed between an insert operation and `getPdo()->lastInsertId()` statement. And this is the reason why the `id` is reseted.

**Comment by pppdns** [comment]
This issue is still happening (Telescope 4.4.0, Laravel 8.19.0). I just spent 4 hours debugging before I found this thread. Can we reopen this ticket? This seems like a serious design flaw to me. We sould at least update the Telescope docs with a warning that we shouldn't use the same database driver for Telescope and the main app, otherwise there may be weird side effects.

When I disable Telescope the issue goes away immediately.

**Comment by driesvints** [comment]
We need a proper way to reproduce this before we can look into this again.

**Comment by piperone** [comment]
@driesvints Would you consider opening this issue again, though? It _is_ an issue that people are experiencing. Thanks.

**Comment by driesvints** [comment]
We've decided to rather document this to suggest using a separate database connection for Telescope. I'll send in a PR to the docs shortly.

**Comment by archilex** [comment]
I've moved telescope to a separate database connection and the problem still persists. 

`TELESCOPE_QUERY_WATCHER=false` continues to be the only way to solve this problem.

**Comment by driesvints** [comment]
If anyone can provide us with a clear step by step way to reproduce this issue I'll re-open it and take another look. Thanks

**Comment by archilex** [comment]
After some digging, in my case the issue comes up during the try/catch block inside Telescope's record method during the RecordQuery call. It seems that the array_merge that is happening on the IncomingEntry->content is overwriting the model id. 

@barryvdh This seems close to what you were referring to? 

In my case this issue only happens with an authenticated user, unlike @bcorcoran 

Commenting out the array_merge bypasses the issue. Obviously not a solution at all (`TELESCOPE_QUERY_WATCHER=false` is still the only viable workaround), but hopefully this additional knowledge gives insight to someone with more experience than me as to what the problem could be.

**Comment by marijnhurkens** [comment]
So we had the same problem in our project, stuff works on non-production environments, but fails on our production environment, where sometimes `$model->getKey()` returns zero.

Our Telescope setup is using filters on production environments:

```
    public function register()
    {
        Telescope::filter(function (IncomingEntry $entry) {
            if ($this->app->isLocal() || app()->environment('staging')) {
                return true;
            }
            
            return $entry->isReportableException() ||
                $entry->isFailedJob() ||
                $entry->isScheduledTask()
                || $entry->hasMonitoredTag()
                ;
        });
    }
```

I found out the issue was gone if I comment out the `hasMonitorTag()` line.

If you follow the calls for that method you will eventually hit monitor() in DatabaseEntriesRepository.php:

```
    public function monitoring()
    {
        return $this->table('telescope_monitoring')->pluck('tag')->all();
    }
```

So `hasMonitorTag()` fires a query the first time which sets last inserted id to zero. To verify I set a breakpoint on the monitor() function above, and the first and last line of the following function (called deep down in Laravels database code, Processor.php):

```
    public function processInsertGetId(Builder $query, $sql, $values, $sequence = null)
    {
        $query->getConnection()->insert($sql, $values);

        $id = $query->getConnection()->getPdo()->lastInsertId($sequence);

        return is_numeric($id) ? (int) $id : $id;
    }
```

- First it hits the insert statement
- **Then it hits the monitor() query**
- And then the lastInsertedId() line

So I think the last inserted id is reset on each query?

I'm not sure how this should be fixed though, telescope seems to hook into the wrong event? Or Laravel should only trigger the `QueryExecuted` (which the QueryWatcher listens to) after the last id has been fetched?

**Comment by marcusmoore** [comment]
Thanks for your comment @marijnhurkens. It explained the issue I was experiencing on `v4.8.2` of Telescope.

**Comment by barryvdh** [comment]
So this resurfaced because of https://github.com/laravel/telescope/pull/1215 ?

**Comment by marcusmoore** [comment]
I believe so since [`v4.8.2`](https://github.com/laravel/telescope/releases/tag/v4.8.2) was the release that included that PR. 

The app I noticed this issue  in was on `v4.8.3`. I downgraded to `v4.8.1` and the issue was fixed. I moved to `v4.8.2` after that and the issue appeared again.

**Comment by SirFaenor** [comment]
I was facing the same issue on telescope 4.9.0 and Laravel 8.83.13, only in production environment.

This trick fixed it, still keeping query watcher on.

https://github.com/laravel/telescope/issues/289#issuecomment-436215837

**Comment by 970Design** [comment]
Also just ran into this issue with telescope 4.9.0 and Laravel 9.19.0.  Works fine locally on docker, breaks on Forge+DO staging & production.

Can also confirm comment 289 fixes.

**Comment by Diagnost1X** [comment]
I had this same issue today, but only in production environment using Laravel 9.19.0 and Telescope 4.9.0.

I checked my published config versus the one in the package and noticed it had changed quite a bit since I published. I updated everything to match and it fixed the issue. I had a play around with the updated values and line that actually fixed this issue was the one linked below. After adding this, the issues stopped.

https://github.com/laravel/telescope/blob/4.x/config/telescope.php#L157

With configs only shallow merging, this becomes an issue for everything in the `watchers` array in the config. It's probably worth mentioning in the upgrade guide to check the changes made to the default config.

**Comment by alimranahmed** [comment]
I am getting the same issue in `laravel/framework v9.34.0`, `laravel/telescope v4.9.4`

And it works when I disable `QueryWatcher` in `telescope.php` config file as below: 

```php
Watchers\QueryWatcher::class => [
    'enabled' => env('TELESCOPE_QUERY_WATCHER', false), // Set to false as some Model::create() call returns id = 0
    'ignore_packages' => true,
    'slow' => 100,
],
```

**Possible alternative solution?**
I am using same database connection as my application is using because this is the default setup when I install telescope. Using seperate DB connection might fix the problem as @themsaid mentioned earlier. But I am not comfortable using a seperate connection as I am not bothered about ignorable speed boost while developing. Besides, default `telescope.php` is using `DB_CONNECTION` env variable which is same for application too. So, it is supposed to work with same DB connection.

**Clue to reproduce?** 
It might not easy to reproduce as I also don't know why it's happening for some models but not for all. I am inserting two rows in two in two tables. One is returning correct id but another one is returing id equal 0. e.g. `Company::create()` is returning company instance with correct id but `Address::create()` is creating new address row correctly with `id` increamented but returning `Address` instance with id property 0. No clue why different Models behaving differently. But it got fixed once I disabled `QueryWatcher` of telescope.

**Comment by nickfls** [comment]
Issue is still present:
L10.5.1
Telescope v4.14.1
Laravel Sail v1.21.3 with mySQL database

*Some* models with identical steps produce this behavior and some - don't.

Moreover:
```php
$model->forceFill($attributes)->save(); // id=0
$model->create($attributes); // id=1
```

Disabling query watcher fixes the issue, but then..

**Comment by wing5wong** [comment]
Following, just ran into this with an older app.
        "laravel/framework": "^9.19",
        "laravel/telescope": "^4.10",

Disabling query watcher and i can then not replicate the issue.
Enable it, and i can consistently get this issue by submitting a few requests in succession (say 1 per .5s, 5-10 times)

**Comment by goldmerc** [comment]
I just ran into this issue and updating the config/telescope.php file to match the latest release worked for me. Thanks @ashleyshenton

**Comment by rizkynat** [comment]
i think you should check if primary key not auto increment where you add id manually. so add this public $incrementing = false;

**Comment by altin-berisha** [comment]
issue still exists in the latest version :( , in my case hardcoding one of the foreign id's caused the issue for example : 
user_id => 1, doesnt work
user_id => User::find(1)->id, works fine

**Comment by rizkynat** [comment]
> i think you should check if primary key not auto increment where you add id manually. so add this public $incrementing = false;

@tnt-altin-berisha
