### ISSUE TITLE
ReflectionException: Class env does not exist

### ISSUE THREAD

**Issue by Noogic** [laravel/telescope#347]
After installing Telescope, all my **Dusk** tests are throwing this error:

```
1) Tests\Browser\PatientsTest::it_can_create_a_patient
ReflectionException: Class env does not exist

/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/Container.php:658
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/Container.php:609
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:733
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/Container.php:1222
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:497
/Users/noogic/data/projects/fisio/app/Providers/TelescopeServiceProvider.php:22
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Support/Collection.php:442
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:61
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Telescope.php:206
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Telescope.php:179
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Telescope.php:209
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Telescope.php:233
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Watchers/CacheWatcher.php:63
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:360
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:209
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:486
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Cache/Repository.php:92
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:323
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Watchers/DumpWatcher.php:43
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/RegistersWatchers.php:48
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/Telescope.php:94
/Users/noogic/data/projects/fisio/vendor/laravel/telescope/src/TelescopeServiceProvider.php:27
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Container/Container.php:572
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:793
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:776
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:777
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php:17
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:206
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:297
/Users/noogic/data/projects/fisio/tests/CreatesApplication.php:18
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:91
/Users/noogic/data/projects/fisio/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:68
/Users/noogic/data/projects/fisio/vendor/laravel/dusk/src/TestCase.php:23
/Users/noogic/data/projects/fisio/tests/Browser/PatientsTest.php:16
```

The only "test" that is passing is the login test.

```
<?php

namespace Tests\Browser;

use App\Entities\Patient;
use App\Entities\User;
use Database\Builders\PatientBuilder;
use Tests\Browser\Pages\Login;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;

class PatientsTest extends DuskTestCase
{
    /** @test */
    function login()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->visit(new Login)
                ->signIn()
            ;
        });
    }

    /** @test */
    function it_can_create_a_patient()
    {
        $this->browse(function (Browser $browser) {
            $browser
                ->pause(200)
                ->visit('/patients')
                ->resize(1024, 768)
                ->waitFor('@patients.create.showForm')
                ->press('@patients.create.showForm')
                ->waitFor('@patients.create.form')
                ->type('@patients.create.name', 'test patient')
                ->type('@patients.create.email', 'tp@test.com')
                ->press('@patients.create.submit')
                ->pause(400)
            ;
        });

        $this->assertDatabaseHas('patients', ['name' => 'test patient', 'email' => 'tp@test.com']);
    }
```

I'm using laravel version **v5.7.12** and phpunit tests are working well, only dusk is failing.

**Comment by davidhemphill** [comment]
I can confirm I have this issue too with the same error. Steps to reproduce:

1. Create a new Laravel app
2. Install Dusk
3. Install Telescope
4. Edit your Dusk test to include:

```php
<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Tests\Browser\Pages\HomePage;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class ExampleTest extends DuskTestCase
{
    /**
     * A basic browser test example.
     *
     * @return void
     */
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/')
                    ->assertSee('Laravel');
        });
    }

    public function testAnotherBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit(new HomePage)
                    ->assertSee('Laravel');
        });
    }
}
```
5. Run your Dusk test.

The first test should pass, but the second one doesn't and gives you the error above.

**Comment by driesvints** [comment]
@Noogic @davidhemphill do the tests pass when you comment out the `DumpWatcher` in your `telescope.php` file? Think this might be the culprit.

**Comment by themsaid** [comment]
We've fixed that, will be available next release.

**Comment by Noogic** [comment]
I still get the same error with v.0.1.8.

Is this supposed to be fixed?

**Comment by zanechua** [comment]
Still occuring in v1.0.5

**Comment by Noogic** [comment]
@zanechua not for me. In my case, I have to disable this watchers in order to make it work:

Command, Dump, Log, Model, Notification, Query and Schedule

**Comment by zanechua** [comment]
@Noogic 

yep agreed. Honestly can't be bothered to try disabling anything to test since it seems to be so random. After upgrading disabling DumpWatcher doesn't work either., but this still exists in the latest revision which is 1.0.6

ping @themsaid

**Comment by foxted** [comment]
I am experiencing this issue as well, but only when I run all my tests, when run individually, they all pass, when run together only one of them passes. Here is an example of the failure message: 

```
30) Tests\Feature\DailyCheckins\WeeklyCheckinsControllerTest::it_allow_users_to_record_a_weekly_checkin_for_themselves
ReflectionException: Class env does not exist

/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:779
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:658
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:609
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735
/var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1222
/var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:482
/var/www/html/app/Providers/TelescopeServiceProvider.php:22
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:60
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:455
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php:61
/var/www/html/vendor/laravel/telescope/src/Telescope.php:232
/var/www/html/vendor/laravel/telescope/src/Telescope.php:201
/var/www/html/vendor/laravel/telescope/src/Telescope.php:235
/var/www/html/vendor/laravel/telescope/src/Telescope.php:358
/var/www/html/vendor/laravel/telescope/src/Watchers/QueryWatcher.php:43
/var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:360
/var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:209
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:826
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:682
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:635
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:459
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:411
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:32
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2595
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1318
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:823
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:788
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:651
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:206
/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php:418
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:207
/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php:181
/var/www/html/tests/Concerns/AttachJwtToken.php:33
/var/www/html/tests/Feature/WeeklyCheckins/WeeklyCheckinsControllerTest.php:20
```

**Comment by bilfeldt** [comment]
Which version of Telescope fixed this @themsaid? It seems to still be present in version `1.0.7`.

**Comment by themsaid** [comment]
Using Laravel `1.0.7` my dusk tests pass.

**Comment by bilfeldt** [comment]
I am using `1.0.7` and both my Dusk tests and my PHPUnit tests are failing, but as @foxted said, only when I run them all and not when I run them individually. Actually it's the **second** test and all trailing tests which fails (so the first passes, and then the rest fails).

I have installed Laravel Telescone to my production (so `composer require` instead of `composer require-dev`) and when testing locally then I am running both PHPUnit tests (`vendor/bin/phpunit`) and Dusk tests (`php artisan dusk`).

What commit should have fixed this @themsaid?

**Comment by themsaid** [comment]
@bilfeldt disable Telescope while running your tests as @mikeminckler suggests. 

The problem before was a cache key stored very early by dusk and causing `Telescope::filter` callback to be invoked and by this time there's no access to the environment available.

**Comment by zanechua** [comment]
I agree with @mikeminckler that this should probably be documented especially with such a breaking incompatibility.

**Comment by bilfeldt** [comment]
Thanks for the explenation @themsaid and @mikeminckle, so here is what I did for PHPUnit:

Only register the `TelescopeServiceProvider` when the environment is not `testing` this is done in `app/Providers/AppServiceProvider.php` as such:
```
/**
 * Register any application services.
 *
 * @return void
 */
public function register()
{
    if ($this->app->environment() != 'testing') {
        $this->app->register(TelescopeServiceProvider::class);
    }
}
```
This works since PHPUnit sets the `APP_ENV=TESTING` as described in the [documentation](https://laravel.com/docs/5.7/testing#environment).

For `Dusk` I simply added the `TELESCOPE_ENABLED=false` to the `.env.dusk.local` as suggested by @mikeminckle

Even though this solves the issue, I don't really think this is a viable solution. This means that all of our tasks are only run without Laravel Telescope, but our production server will be running with Laravel Telescope. Does anyone know what is causing this?

**Comment by Livijn** [comment]
You could just add `<env name="TELESCOPE_ENABLED" value="false"/>` to the `phpunit.xml`-file.

**Comment by bilfeldt** [comment]
@Livijn just as proposed [here](https://github.com/laravel/telescope/issues/347#issuecomment-442937226):

> An alternative solution could be to add TELESCOPE_ENABLED=false to the phpunit.xml file.

But my concern is still that this means Laravel Telescope is disabled while we are running Dusk or PHPUnit tests, but in production Laravel Telescope is running, so the tests are no longer valid as I see it.

**Comment by adelynx** [comment]
I add TELESCOPE_ENABLED=false to my testing environment file and it's work fine. Thanks

**Comment by lionslair** [comment]
> I add TELESCOPE_ENABLED=false to my testing environment file and it's work fine. Thanks

What about dusk tests. I am still getting a lot of problem with dusk tests even after adding this flag

**Comment by vesper8** [comment]
@Livijn's solution works good. This is not only causing Dusk tests to fail but also regular phpunit tests

Wish this was documented, or the line should be added to the phpunit.xml file when running telescope:install

**Comment by mvdnbrk** [comment]
- Install a fresh copy of Laravel `v5.7.16`
- Install Telescope `v1.0.8`
- Run `phpunit`

```
ReflectionException: Class env does not exist
```

Just needed an hour or so to figure this out :unamused:

**Comment by vesper8** [comment]
@themsaid can't anything be done about this? it's still affecting lots of us

**Comment by lionslair** [comment]
See the installation docs. Not sure if it was always there but solved my issues.

Installing Only In Specific Environments

Remove it from config/app.php and only allow it to be included on the environments you want it.

eg

`  if (! $this->app->environment(['dusk', 'testing'])) {
            $this->app->register(TelescopeServiceProvider::class);
        }`

**Comment by claytonrcarter** [comment]
@mvdnbrk Another example (as happened to me):

- Existing Laravel 5.7 app
- run `phpunit` - all tests pass
- install Telescope
- run `phpunit` - `ReflectionException: Class env does not exist`

While this is easy to fix (either with `TELESCOPE_ENABLED=false` in `phpunit.xml` or, as @lionslair mentioned, in `AppServiceProvider`) the first impression certainly isn't great.

**Comment by mvdnbrk** [comment]
I ran into this same issue when updating packages with `composer update` in one of my projects.
This updated Telescope from v1.0.6 to v1.0.8.

Run `phpunit` and everything blows up with `ReflectionException: Class env does not exist`.

This can be really confusing to figure out that this is caused by Telescope.

This seems to be introduced since version 1.0.7.

**Comment by lionslair** [comment]
My issue only occured with dusk. I  was able to run individual dusk tests but not a file or directory. Threw that "ReflectionException: Class env does not exist." and also malformed corrupted database.

After removing the service provider from app/config.php and loading it when not in testing and dusk environments problem was instantly solved. But took a few weeks to work out. Was aware it started as soon as telescope was added though but WHY is still unknown. I guess it's to do with bootstrapping or something.

**Comment by sustained** [comment]
This issue has been driving me up the wall for hours.

**Comment by ermand** [comment]
As suggested by @Livijn , by adding `<env name="TELESCOPE_ENABLED" value="false"/>` to the `phpunit.xml` file it fixes this issue. 

@themsaid  since this is an issue with a fresh install of laravel + laravel/telescope, would it be possible to have this note in the official documentation in laravel website? Thanks a lot for the great work and support 😃

**Comment by sustained** [comment]
IMHO this should be the default configuration of `phpunit.xml`. EIther that or upon installation of Laravel Telescope it should be added. It needs to be documented too.

**Comment by lionslair** [comment]
the <env name="TELESCOPE_ENABLED" value="false"/> solution made no difference for me. 

Also dusk appears to create its own phpunit xml file. Did not solve the issue when I added it there either.

**Comment by nathanbarrett** [comment]
I am still having this exact issue as well. Laravel 5.7.16 and Telescope 1.0.9 . I have `TELESCOPE_ENABLED=false` set in `phpunit.xml` , `phpunit.dusk.xml`, and `.env.dusk.local` and I am still getting the error

**Comment by aocneanu** [comment]
Temporary solution, set:

 `'enabled' => env('TELESCOPE_ENABLED', env('APP_ENV') !== 'testing'),`

in telescope.php

**Comment by talovicnedim** [comment]
+1 for documenting.

`TELESCOPE_ENABLED=false` in `.env.testing` works for me.

**Comment by stonkeep** [comment]
I've runned
`php artisan clear
php artisan config:clear
`
Solved for me

**Comment by njoguamos** [comment]
> You could just add `<env name="TELESCOPE_ENABLED" value="false"/>` to the `phpunit.xml`-file.

This worked for me like a charm

**Comment by zhorton34** [comment]
**Two Solutions:**


**Solution One:**
(mentioned several times above):

1. Go to `phpunit.xml`
2. Add `<env name="TELESCOPE_ENABLED" value="false"/>`

**Solution Two:**
1. Copy `.env` to `.env.testing`
2. Change `TELESCOPE_ENABLED=false` to `TELESCOPE_ENABLED=true`

**Comment by yaranliu** [comment]
None worked for me. 
I have manually paused monitoring from `/telescope` dashboard and it worked.

**Comment by andrewgorpenko** [comment]
I am not using Dusk and this error still persist in some tests. This should definitely be documented.

**Comment by dillingham** [comment]
just ran into this issue, can't telescope check if `testing`?

**Comment by Punksolid** [comment]
What if I want to track a single test with telescope ?

**Comment by bolechen** [comment]
just ran into this issue, can't telescope check if testing?

<env name="TELESCOPE_ENABLED" value="FALSE" />

added to my phpunit.xml

**Comment by WouterFlorijn** [comment]
I still have this issue with Laravel 5.8 and Telescope 2.0.2.

Obviously, disabling stuff for tests is a terrible workaround. If Telescope would cause any errors in production, they wouldn't be caught, and the application would crash once deployed.

Please create a fix for this.

**Comment by lionslair** [comment]
I noticed it was still somehow getting involved. In order to stop it I'm only allowing the service provider to get loaded for the environment I want it. Seems to be the best solution. Using the disable flag still does nothing

⁣Sent from my mobile​

**Comment by amadeann** [comment]
I was getting the same error, and even with `TELESCOPE_ENABLED=false` in `phpunit.xml` it didn't work. I only got the tests to pass after runnnig `php artisan optimize:clear` first.

**Comment by kevinb1989** [comment]
Has this issue been solved? I am still having this issue with Laravel 5.7.28 and Telescope 1.2.

Update phpunit.xml or .env files works for me. But I would rather not doing so.

<img width="536" alt="Screen Shot 2019-06-15 at 6 35 02 pm" src="https://user-images.githubusercontent.com/7900186/59549139-96d93c00-8f9c-11e9-88cb-1546bfb8b2ec.png">

**Comment by Shelob9** [comment]
If anyone else gets confused like I did about where to put the env variable in phpunit.xml, it goes inside the php tag.

```
<phpunit>
    <php>
        <env name="TELESCOPE_ENABLED" value="false"/>
    </php>
</phpunit>
```

**Comment by sustained** [comment]
Why is this closed? Lots of people are still having this issue.

**Comment by WyattCast44** [comment]
Update for those still experiencing this issue, if you commonly run `config:cache` while developing, the suggested solution of adding `TELESCOPE_ENABLED=false` to `phpunit.xml` will only actually work if you run `optimize:clear`. 

I commonly run `config:cache` during dev, should cached config take precedence over `phpunit.xml`? Is this something that can be checked when running tests? Not sure if this the intended behavior @taylorotwell @themsaid ?

**Comment by mikemunger** [comment]
Regarding `config:cache` - I actually inherited an app where config:cache could not be run without error, so now that I have fixed that -- I am hoping my tests CAN test against the config:cache values to prove nothing is broken while tests are running.  Based on all this though, so far it seems you cannot have a config:cache and run tests without this error.  :(

**Comment by cedaesca** [comment]
> 
> 
> Update for those still experiencing this issue, if you commonly run `config:cache` while developing, the suggested solution of adding `TELESCOPE_ENABLED=false` to `phpunit.xml` will only actually work if you run `optimize:clear`.
> 
> I commonly run `config:cache` during dev, should cached config take precedence over `phpunit.xml`? Is this something that can be checked when running tests? Not sure if this the intended behavior @taylorotwell @themsaid ?

this fixed it for me

**Comment by opejovic** [comment]
> > Update for those still experiencing this issue, if you commonly run `config:cache` while developing, the suggested solution of adding `TELESCOPE_ENABLED=false` to `phpunit.xml` will only actually work if you run `optimize:clear`.
> > I commonly run `config:cache` during dev, should cached config take precedence over `phpunit.xml`? Is this something that can be checked when running tests? Not sure if this the intended behavior @taylorotwell @themsaid ?
> 
> this fixed it for me

+1

**Comment by DiederikvandenB** [comment]
People have suggested disabling Telescope in testing environments to resolve this issue, but that was not really an answer for me since I like to use Telescope to debug my failing tests.

I found out that commenting out the default `Telescope::filter` function in the `TelescopeServiceProvider` resolved the issue. Apparently, inside this function and while in testing env, something weird is going on. Anyway, my final solution:

```php
        // Disable the filter while in local or testing environment.
        $disableFilter = $this->app->environment(['local', 'testing']);
        Telescope::filter(function (IncomingEntry $entry) use ($disableFilter) {
            if ($disableFilter) {
                return true;
            }

            return $entry->isReportableException() ||
                $entry->isFailedJob() ||
                $entry->isScheduledTask() ||
                $entry->hasMonitoredTag();
        });
```

**Comment by gordonhung** [comment]
Same case with @DiederikvandenB , I would like to use Telescope in the test and found same root cause. The different is, I use ```App``` Facades to determinate the environment because that use ```$this->app()``` trigger same error: ```ReflectionException: Class env does not exist```.

```php
if ($this->app->isLocal() || $this->app->runningUnitTests())
if ($this->app->environment(['local', 'testing']))
```

In short, the ```\App\Providers\TelescopeServiceProvider::register``` as changed below:

```php
public function register()
{
    // Telescope::night();

    $this->hideSensitiveRequestDetails();

    Telescope::filter(function (IncomingEntry $entry) {
        if (App::environment(['local', 'testing'])) {
            return true;
        }

        return $entry->isReportableException() ||
            $entry->isFailedRequest() ||
            $entry->isFailedJob() ||
            $entry->isScheduledTask() ||
            $entry->hasMonitoredTag();
    });
}
```

**Comment by Patabugen** [comment]
To add to @gordonhung 's workaround:

You need to add the Use for the facade, which is this: (it always takes me a bit of time to find these):
`use Illuminate\Support\Facades\App`

And I also needed to add it to the `hideSensitiveRequestDetails` method:
`\App\Providers\TelescopeServiceProvider::hideSensitiveRequestDetails`

**Comment by pedzed** [comment]
I'm not sure why this is closed. This issue is still present.

@gordonhung's workaround works for great for me:
> ```php
> if (App::environment(['local', 'testing'])) {
> ```

Or as I like to do, replace the two instances in `app/Providers/TelescopeServiceProvider.php`:
```php
if ($this->app->isLocal()
```
to:
```php
if (app()->environment(['local', 'testing'])) {
```

**Comment by klocus** [comment]
Why this issue is closed? That error still exists.

**Comment by quaidesbalises** [comment]
I confirm, still have the issue

**Comment by dillingham** [comment]
Open a new issue. Likely not seeing it.

**Comment by pedzed** [comment]
> Open a new issue. Likely not seeing it.

If possible, it's better to reopen this one.

@Noogic could you reopen this issue?

**Comment by Mloweedgar** [comment]
> I add TELESCOPE_ENABLED=false to my testing environment file and it's work fine. Thanks

I did the same and It worked like charm!

**Comment by ChrisThompsonTLDR** [comment]
We are seeing this when using Dusk and Telescope, but only when a Dusk test utilizes the `setUp()` method.

Disabling Telescope in `phpunit.xml` didn't seem to work.

Removing `App\Providers\TelescopeServiceProvider.php` from `config/app.php` worked.

**Comment by christopherarter** [comment]
Still seeing this issue on Laravel `7.20.0`, Telescope `3.5.0` and Dusk `v6.4.1`.

I can run each test separately just fine, but `php artisan dusk` fails with `Class env does not exist`. 

I have added `<server name="TELESCOPE_ENABLED" value="false"/>` in the correct place in the `phpunit.xml` file, run `optimize:clear` and `config:cache`, and I'm still getting this issue.

**Comment by WyattCast44** [comment]
@christopherarter did you try running `config:clear`? 

It sounds like you ran `optimize:clear` and then `config:cache` which would negate the effect of running `optimize:clear`?

Hope this helps 🙂

**Comment by christopherarter** [comment]
@WyattCast44 unfortunately not. Still having this issue.

It's basically not recognizing the values in the `phpunit.xml` file for any tests beyond the first one.

 _However_, if anyone is still having this problem after trying the answers above, though this is not a fix, I ended up just putting `TELESCOPE_ENABLED=false` in my `.env.dusk.local` file and it's working.

**Comment by shanerbaner82** [comment]
Not using dusk, added `<env name="TELESCOPE_ENABLED" value="false"/>` to `phpunit.xml` and everything seems to be working fine for me.

**Comment by tomheadifen** [comment]
You can change the default to false for telescope by updating your `config/telescope.php` file.

```
    /*
    |--------------------------------------------------------------------------
    | Telescope Master Switch
    |--------------------------------------------------------------------------
    |
    | This option may be used to disable all Telescope watchers regardless
    | of their individual configuration, which simply provides a single
    | and convenient way to enable or disable Telescope data storage.
    |
    */

    'enabled' => env('TELESCOPE_ENABLED', false), // Change from true to false here.
```

You will then have to set: `TELESCOPE_ENABLED=true` in your .env file. This will ensure that you don't have it accidentally turned on in environments you don't want such as production and unit testing.

**Comment by josezenem** [comment]
Recently upgraded to Laravel 8 from Laravel 7, I just started experiencing this issue.  I am running PHP 7.4.

After some debugging, I found that PHPUnit will ignore `false` as a value, but if you type any other value it picks it up, there seems to be something odd with how the config loads the `false` value.  Not sure if this is an issue with PHP Unit or if it's an issue with Laravel.  it also only happens with `<server` but if you use `<env` per @shanerbaner82 it will work fine as well.

This will not work

```
<server name="TELESCOPE_ENABLED" value="false"/>
```

But if you update it to this, it will work

```
<server name="TELESCOPE_ENABLED" value="0"/>
```

**Comment by leandromatos** [comment]
Thanks @josezenem! I spent 4 hours trying to solve this problem.

**Comment by Shaggy84675** [comment]
> 
> 
> Recently upgraded to Laravel 8 from Laravel 7, I just started experiencing this issue. I am running PHP 7.4.
> 
> After some debugging, I found that PHPUnit will ignore `false` as a value, but if you type any other value it picks it up, there seems to be something odd with how the config loads the `false` value. Not sure if this is an issue with PHP Unit or if it's an issue with Laravel. it also only happens with `<server` but if you use `<env` per @shanerbaner82 it will work fine as well.
> 
> Editing file `phpunit.xml`
> 
> This will not work
> 
> ```
> <server name="TELESCOPE_ENABLED" value="false"/>
> ```
> 
> But if you update it to this, it will work
> 
> ```
> <server name="TELESCOPE_ENABLED" value="0"/>
> ```

You saved my day! Same problem on Laravel 8. After this change I've also had to clear config cache using `php artisan config:clear`

**Comment by fefogarcia** [comment]
> Recently upgraded to Laravel 8 from Laravel 7, I just started experiencing this issue. I am running PHP 7.4.
> 
> After some debugging, I found that PHPUnit will ignore `false` as a value, but if you type any other value it picks it up, there seems to be something odd with how the config loads the `false` value. Not sure if this is an issue with PHP Unit or if it's an issue with Laravel. it also only happens with `<server` but if you use `<env` per @shanerbaner82 it will work fine as well.
> 
> Editing file `phpunit.xml`
> 
> This will not work
> 
> ```
> <server name="TELESCOPE_ENABLED" value="false"/>
> ```
> 
> But if you update it to this, it will work
> 
> ```
> <server name="TELESCOPE_ENABLED" value="0"/>
> ```

I was just having the same issue after upgrading to Laravel 8 and this is the only thing that fixed it. Thank you.

**Comment by Blair2004** [comment]
Sometimes, you might need to run `composer dump-autoload`.

**Comment by valehasadli** [comment]
> setting `TELESCOPE_ENABLED=false` in my `.env.dusk.local` or `.env` solved the issue.
> 
> Not sure this is really an issue but maybe needs to be documented.

Thanks! It works! Warning, if you're using docker or sail environment, don't forget to run clear cache commands and or delete bootstrap cache folder files.

**Comment by valehasadli** [comment]
This error still actual. 

after `TELESCOPE_ENABLED=false` the `php artisan test` command is worked, but it's not the way to handle this issue.

I need a real solution to work at the same time with each functionality. Because after `TELESCOPE_ENABLED = false` command telescope does not work. And it's too much time every time turn on / turn off.

**Comment by wocodes** [comment]
Also, as an alternative, just changing this
`'enabled' => env('TELESCOPE_ENABLED', true),` to
`'enabled' => env('TELESCOPE_ENABLED', config('app.env')!=='testing'),`

in your telescope config file solves it too. As telescope will only be activated when the env is changed to testing by phpunitxml.

**Comment by Dhermann27** [comment]
Same here. It'd really be nice to see telescope entries for my dusk testcases. +1

**Comment by TWithers** [comment]
Just ran into this issue. Wanted to use telescope with dusk as well. Fix for me was to use `config()->get('app.env')` instead of `$this->app->environment()` in the TelescopeServiceProvider.php filter.

```
        Telescope::filter(function (IncomingEntry $entry) {
            if (in_array(config()->get('app.env'),['local','testing'])) {
                return true;
            }

            return $entry->isReportableException() ||
                   $entry->isFailedRequest() ||
                   $entry->isFailedJob() ||
                   $entry->isScheduledTask() ||
                   $entry->hasMonitoredTag() ||
                   $entry->isSlowQuery();
        });
```
