### ISSUE TITLE
Telescope keeps scanning 

### ISSUE THREAD

**Issue by ChinwalPrasad** [laravel/telescope#493]
Hi! I just did a fresh install of Laravel Telescope and followed all steps. I am able to access telescope at 
/telescope and at this point I get a blank screen.
<img width="1440" alt="screen shot 2018-12-11 at 8 53 44 pm" src="https://user-images.githubusercontent.com/40767861/49844038-f012a980-fd86-11e8-952d-a8e4f3eabf64.png">

But then when i try to access Requests / Logs / Exceptions ( Actually on all tabs) I get the below error

<img width="1440" alt="screen shot 2018-12-11 at 8 50 25 pm" src="https://user-images.githubusercontent.com/40767861/49844070-11739580-fd87-11e8-9821-5babd945b32c.png">

What I tried:
1. When i run php artisan route:list I can find all the telescope routes. 
2. I tried clearing cache. But it did not help.
3. UnInstalled and installed fresh copy on new laravel project
Any help is appreciated.

**Comment by ChinwalPrasad** [comment]
![capture](https://user-images.githubusercontent.com/40767861/49878913-5da5f080-fdee-11e8-9d5e-f846c283d6fe.PNG)
This is what i get when i do php artisan route:list.

I tried to install telescope in dev. But the result is the same.

Thanks again!

**Comment by Sylk** [comment]
Having a similar issue over here. @ChinwalPrasad you never found a solution on Laracasts I saw that thread. Seems like others are experiencing this problem also.

**Comment by ChinwalPrasad** [comment]
Yeah @Sylk I saw couple issues which are similar but none could solve my issues. Check out this issue #496 .

**Comment by genesiiis12** [comment]
Did you already migrate your database? I had the same problem. I just forgot to migrate my database haha

**Comment by genesiiis12** [comment]
> Hi! I just did a fresh install of Laravel Telescope and followed all steps. I am able to access telescope at
> /telescope and at this point I get a blank screen.
> <img alt="screen shot 2018-12-11 at 8 53 44 pm" width="1440" src="https://user-images.githubusercontent.com/40767861/49844038-f012a980-fd86-11e8-952d-a8e4f3eabf64.png">
> 
> But then when i try to access Requests / Logs / Exceptions ( Actually on all tabs) I get the below error
> 
> <img alt="screen shot 2018-12-11 at 8 50 25 pm" width="1440" src="https://user-images.githubusercontent.com/40767861/49844070-11739580-fd87-11e8-9821-5babd945b32c.png">
> 
> What I tried:
> 
> 1. When i run php artisan route:list I can find all the telescope routes.
> 2. I tried clearing cache. But it did not help.
> 3. UnInstalled and installed fresh copy on new laravel project
>    Any help is appreciated.

Did you already migrate your database? I had the same problem. I just forgot to migrate my database haha

**Comment by genesiiis12** [comment]
Did you already migrate your database? I had the same problem. I just forgot to migrate my database haha

**Comment by ChinwalPrasad** [comment]
@genesiiis12 Yes I actually can see the data in the tables. I think it is the issue of url over reverse proxy. Not sure but that's what others are saying

**Comment by striderxfossility** [comment]
I am also having this problem, on localhost it works fine, but on my actual website it keeps scanning with the js error

Uncaught (in promise) Error: Request failed with status code 500
    at LYNF.p.exports (app.js?id=***)
    at Rn+g.p.exports (app.js?id=***)
    at XMLHttpRequest.A.(anonymous function) (https://www.***/vendor/telescope/app.js?id=***)

**Comment by sagahria** [comment]
hi , @ChinwalPrasad , I got the same issue on telescope , it keeps  scanning. seems you've found out how to solve it , would you mind telling me the solution ? I will appreciate it :-)

**Comment by striderxfossility** [comment]
Hi sagahria,

i fixed this with [link](https://github.com/laravel/telescope/issues/621)

**Comment by ChinwalPrasad** [comment]
@sagahria I haven't found the solution yet but I would definitely give @striderxfossility's solution a try.
Thanks @striderxfossility :)

**Comment by ChinwalPrasad** [comment]
@striderxfossility, @sagahria  the solution mentioned by @striderxfossility didn't work for me. I do have  the file EntryQueryOptions.php. I still get the same error and I don't see anything in my logs which is weird.

**Comment by sagahria** [comment]
@ChinwalPrasad  thank you for following the question , let you know if I found it out !

**Comment by cococococococo** [comment]
same problem here

**Comment by Menelion** [comment]
Having the same error on dev, no luck.

**Comment by rupeszh** [comment]
Solution to the problem for me is adding telescope in VerifyCsrfToken middleware.i:e
protected $except = [
        'telescope/*'
    ];
}

**Comment by Arthuralentejo** [comment]
Having the same error, no solution on this thread have worked for me. Does anyone have a clue of what is causing this?
