### ISSUE TITLE
Too many parameter bindings during insert when using sqlsrv database driver

### ISSUE THREAD

**Issue by Namoshek** [laravel/telescope#614]
- Telescope Version: 2.0.2
- Laravel Version: 5.8.7
- PHP Version: 7.2.13
- Database Driver & Version: sqlsrv & pdo_sqlsrv  @ v5.3.0

### Description:

When performing heavy operations during a request or command execution where too many  recordable actions are performed, it happens very frequently that Telescope is not able to store the captured entries. Recordable actions may be events, logs or any other watcher objective.

The capturing itself seems to work fine (even when capturing 10k+ actions), but when storing the recordings, nothing is stored and Telescope crashes with the error:
> PDOException: SQLSTATE[IMSSP]: Tried to bind parameter number 2101.  SQL Server supports a maximum of 2100 parameters.

### Steps To Reproduce:

- Use sqlsrv database driver (probably the only one with a hard-limit on bindable parameters).
- Fire enough events or perform enough other recordable stuff during a request or command execution.

### Initial Analysis:

My guess is that this simply happens because Telescope tries to store all recordings right before termination of the request/command:

https://github.com/laravel/telescope/blob/92bc1f7566b8f0cecef036129caf8e9451b7b117/src/ListensForStorageOpportunities.php#L41-L46

https://github.com/laravel/telescope/blob/92bc1f7566b8f0cecef036129caf8e9451b7b117/src/Telescope.php#L540-L565

https://github.com/laravel/telescope/blob/92bc1f7566b8f0cecef036129caf8e9451b7b117/src/Storage/DatabaseEntriesRepository.php#L104-L125

The rather obvious workarounds would be to:
1. store recordings as soon as the `$entriesQueue` reaches a certain limit
2. determine the ideal chunk size based on the used database driver
3. reduce the chunk size used by the `DatabaseEntriesRepository`

As 1) is a design change and most likely BC-breaking and 2) could still lead to undesired results in the future (or with custom database drivers), I'd aim for 3) and make the chunk size configurable. This way it remains BC and sqlsrv users can fix the issue themselves. A chunk size of around 250 should fix the issue as the `telescope_entries` table has 8 columns (even though not all 8 are given during an insert).

**Comment by FrittenKeeZ** [comment]
The chunk size won't fix it alone, since you can end up with a single entry having over 2100 bindings.
I don't know if it's even possible to fix.

**Comment by Namoshek** [comment]
Now I'm curious how a single entry can have over 2100 bindings...?

I'm using the suggested fix in production for a few weeks now, without any further issues so far. I'm not tagging or monitoring entries though.

**Comment by FrittenKeeZ** [comment]
For me, It's happening for a certain request with a lot of queries and models being returned.

**Comment by Namoshek** [comment]
Alright, but that's not _a single entry_ as far as I can see. What you described is exactly the use case I fixed with the linked PR. A single entry with over 2100 bindings would mean to me that there is an `IncomingEntry` object with over 2100 parameters, which is simply not possible (the database table has not this many columns, if you know what I mean). Therefore, chunking should ensure only a limited amount of records is inserted at the same time, limiting the parameter bindings.

I'm running a chunk size of 250 at the moment.

**Comment by FrittenKeeZ** [comment]
What you say makes 100% sense, but I did try the fix and the error still occurs - even set the chunk size down to 10, but it seems it somehow gets cached and fixed to 1000.

I'm using `"laravel/telescope": "2.0.x-dev#e5f9512"` which should work.

**Comment by Namoshek** [comment]
Two ideas:
- Are you running a cached config? Maybe, just for the sake of testing, add a `var_dump(config('telescope.storage.database.chunk_size'))` somewhere.
- If you use your own `TelescopeServiceProvider`, you should make sure to add the changes made to the default implementation in the linked PR.

**Comment by FrittenKeeZ** [comment]
It was the config which had been cached by another user, so the file permissions were all messed up!
Removing `boostrap/cache/config.php` with said user made it work - thanks for the help!
